# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
gem: [jekyll-paginate, jekyll-gists]

# Setup
title:            Sydney Zink
tagline:          'A Jekyll theme'
description:      'Researching in the <a href="https://cs.brown.edu/people/epavlick/students.html" target="_blank">Lunar Lab</a> under <a href="https://cs.brown.edu/people/epavlick/index.html" target="_blank">Ellie Pavlick</a> at Brown University.'
url:              http://hyde.getpoole.com
baseurl:          https://thinkzink.github.io/hyde/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
